/**
 * Gestion des Marchés API
 * API pour la gestion des marchés
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Tache } from './tache';
import { User } from './user';

export interface Commentaire { 
    idCommentaire?: number;
    contenu?: string;
    etat?: Commentaire.EtatEnum;
    task?: Tache;
    employee?: User;
}
export namespace Commentaire {
    export type EtatEnum = 'URGENT' | 'QUOTIDIEN' | 'INFORMATIF';
    export const EtatEnum = {
        URGENT: 'URGENT' as EtatEnum,
        QUOTIDIEN: 'QUOTIDIEN' as EtatEnum,
        INFORMATIF: 'INFORMATIF' as EtatEnum
    };
}