/**
 * Gestion des Marchés API
 * API pour la gestion des marchés
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Market } from './market';
import { Service } from './service';
import { User } from './user';

export interface Entreprise { 
    idEntreprise?: number;
    nom?: string;
    adresse?: string;
    services?: Array<Service>;
    employees?: Array<User>;
    directeur?: User;
    markets?: Array<Market>;
    chefService?: Array<User>;
}