/**
 * Gestion des Marchés API
 * API pour la gestion des marchés
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Entreprise } from './entreprise';
import { Project } from './project';

export interface Market { 
    idMarket?: number;
    nom?: string;
    description?: string;
    entreprise?: Entreprise;
    project?: Project;
}