/**
 * Gestion des Marchés API
 * API pour la gestion des marchés
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Market } from './market';
import { Tache } from './tache';

export interface Project { 
    idProject?: number;
    nom?: string;
    description?: string;
    dateDebut?: Date;
    dateFin?: Date;
    budget?: number;
    statusProject?: Project.StatusProjectEnum;
    market?: Market;
    tasks?: Array<Tache>;
    fileName?: string;
}
export namespace Project {
    export type StatusProjectEnum = 'accepté' | 'invalide';
    export const StatusProjectEnum = {
        Accept: 'accepté' as StatusProjectEnum,
        Invalide: 'invalide' as StatusProjectEnum
    };
}