/**
 * Gestion des Marchés API
 * API pour la gestion des marchés
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Entreprise } from './entreprise';
import { User } from './user';

export interface Service { 
    idService?: number;
    libelle?: string;
    employees?: Array<User>;
    chefService?: User;
    entreprise?: Entreprise;
}