/**
 * Gestion des Marchés API
 * API pour la gestion des marchés
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Commentaire } from './commentaire';
import { Project } from './project';

export interface Tache {
    idTask: number;
    libelle: string;
    deadline: Date;
    description: string;
    duration: string;
    etat: Tache.EtatEnum;
    project: Project;
    commentaires: Array<Commentaire>;
}
export namespace Tache {
    export type EtatEnum = 'en_attente' | 'en_cours' | 'validée' | 'non_validée';
    export const EtatEnum = {
        EnAttente: 'en_attente' as EtatEnum,
        EnCours: 'en_cours' as EtatEnum,
        Valide: 'validée' as EtatEnum,
        NonValide: 'non_validée' as EtatEnum
    };
}
