/**
 * Gestion des Marchés API
 * API pour la gestion des marchés
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Commentaire } from './commentaire';
import { Entreprise } from './entreprise';
import { Role } from './role';
import { Service } from './service';

export interface User { 
    idUser?: number;
    nom?: string;
    prenom?: string;
    email?: string;
    password?: string;
    role?: Role;
    entreprise?: Entreprise;
    service?: Service;
    commentaire?: Commentaire;
}